# Simple docker template
version: '3'
services:
  app:
    image: akasadev/akasa-node-14-latest:1
    working_dir: '/opt/app' 
    command : >
      bash -c "
       tail -f > /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/app"
    environment:
      - 'CHOKIDAR_USEPOLLING=true'
